Issue/173
adaptlearning/adapt-contrib-core pull request #201
Opened 2022-07-27 11:16 UTC by chris-steele

[//]: # (Please title your PR according to eslint commit conventions)
Update: provide alternative heading for AT (fixes #173)

[//]: # (Link the PR to the original issue)
https://github.com/adaptlearning/adapt-contrib-core/issues/173

### Update
* Provide an alternative heading for Assistive Technology if no visual heading is required

2022-07-27 11:19 UTC, cahirodoherty-learningpool approved these changes
👀

2022-07-27 11:29 UTC, oliverfoster requested changes

2022-07-27 11:29 UTC, oliverfoster commented on templates/notifyPopup.hbs
> +          {{/if}}
```suggestion
        {{else if altTitle}}
        <div class="notify__title aria-label" id="notify-heading">
          <div class="notify__title-inner" {{{a11y_attrs_heading 'notify'}}}>
            {{{compile altTitle}}}
          </div>
        </div>
```
Reference https://handlebarsjs.com/guide/block-helpers.html#conditionals

2022-07-28 14:25 UTC, oliverfoster commented on templates/notifyPopup.hbs
> +            <div class="notify__title-inner" {{{a11y_attrs_heading 'notify'}}}>
a11y_ helper thing again

2022-08-15 09:11 UTC, oliverfoster approved these changes

2022-08-16 21:52 UTC, joe-replin approved these changes
Tested in v5.19.6 of the FW and working well.

2022-08-17 01:42 UTC, merged