#2604 ensure score sent to LMS before status
adaptlearning/adapt-contrib-core pull request #30
Opened 2021-11-01 16:54 UTC by chris-steele

See https://github.com/adaptlearning/adapt-contrib-spoor/pull/222

2021-11-03 12:37 UTC, cahirodoherty-learningpool approved these changes
👀

2021-11-03 12:58 UTC, oliverfoster requested changes

2021-11-03 12:58 UTC, oliverfoster commented on js/tracking.js
> +    Adapt.offlineStorage.set('score', this._assessmentState.score, 0, this._assessmentState.maxScore);
```suggestion
    Adapt.offlineStorage.set('score', this._assessmentState.score, this._assessmentState.minScore, this._assessmentState.maxScore);
```
Assessment state also has a `minScore` now https://github.com/adaptlearning/adapt-contrib-assessment/pull/132

2021-11-03 13:13 UTC, oliverfoster approved these changes
pending version bump

2021-11-03 13:20 UTC, oliverfoster commented
Sorry Chris, this probably should be a minor version bump. So 6.1.0 as it's a feature addition really rather than a bugfix. Fine line in this case.

2021-11-03 13:45 UTC, cahirodoherty-learningpool approved these changes
👀

2021-11-15 14:32 UTC, eleanor-heath approved these changes

2021-11-22 10:01 UTC, merged