Update: added _lang property (fixes #470)
adaptlearning/adapt-contrib-core pull request #471
Opened 2023-11-14 15:06 UTC by chris-steele

#470

2023-11-15 12:37 UTC, taylortom requested changes

2023-11-15 16:28 UTC, chris-steele commented on schema/content.schema.json
> +        "editorAttrs": { "disabled": true }
Amended

2023-11-15 16:28 UTC, chris-steele commented on schema/content.schema.json
> +        "editorAttrs": { "disabled": true }
Amended

2023-11-20 10:25 UTC, chris-steele commented
FYI this PR will likely be binned soon as we have concluded that `_lang` is not required.

2023-11-21 12:24 UTC, taylortom commented
Nothing to see here...after some discussion it's been decided that this change isn't needed on the framework side.

2023-11-21 12:24 UTC, closed without merging