Focus should be given to Learning Objective pop ups when achieved
adaptlearning/adapt-contrib-core pull request #50
Opened 2021-12-02 15:27 UTC by eleanor-heath

2021-12-02 16:03 UTC, cahirodoherty-learningpool commented on js/views/notifyPopupView.js
> +
Minor: I think we are trying to explicitly import wherever possible
```import Backbone from 'backbone';```

2021-12-02 16:04 UTC, cahirodoherty-learningpool approved these changes
👀

2021-12-02 17:21 UTC, ethan-lp approved these changes

2022-01-11 14:39 UTC, lc-alexanderbenesch approved these changes
👍

2022-02-23 17:02 UTC, oliverfoster requested changes
Linting warnings in notifyPopupView, notifyPushView and notifyView

Tested in Firefox, IE11, Chrome, with NVDA and JAWS. Reading perfectly.

2022-02-24 11:21 UTC, oliverfoster approved these changes

2022-02-24 11:22 UTC, merged