Fix for inview percentages
adaptlearning/adapt-contrib-core pull request #65
Opened 2022-02-17 15:45 UTC by danielghost

https://github.com/adaptlearning/adapt-contrib-core/issues/63.

2022-02-21 18:54 UTC, oliverfoster requested changes

2022-02-21 19:01 UTC, oliverfoster commented on libraries/inview.js
> +      var isRightOnScreen = (measure.percentFromRight >= 0 && measure.percentFromRight < 100);
No. As 0 perfect away from Tom or bottom is onscreen.

2022-02-21 19:01 UTC, oliverfoster approved these changes

2022-02-21 19:19 UTC, cahirodoherty-learningpool approved these changes
👀

2022-02-23 11:36 UTC, lc-alexanderbenesch approved these changes
👍

2022-02-23 12:12 UTC, merged